# /usr/local/bin/docker-compose -f /docs/dev-ops/environment/environment-docker-compose-2.4.yml up -d
version: '3.3'
# docker-compose -f docker-compose.yml up -d
services:
  yusi:
    build:
      context: .
      dockerfile: Dockerfile
    image: yusi:latest
    container_name: yusi
    restart: on-failure
    ports:
      - "611:611"
      - "9090:9090"
    environment:
      - TZ=PRC
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./log:/data/log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
    external: true
